from PySide6.QtWidgets import QMainWindow


class CollapsiblePanel(QMainWindow):
    def __init__(self):
        super().__init__()
        self.isTop: bool = ...
        self.alwaysOnEdge: bool = ...
        self.collapseOnOpen: bool = ...
        self.isLocked: bool = ...
        self.winIsExpand: bool = ...
        self.settingsIsExpand: bool = ...
        self.hasDraggingWidget: bool = ...
        self.hasActivePopup: bool = ...
        self.firstStart: bool = ...
        self.isCollapsibleFromUser: bool = ...

    def switchTheme(self, theme: str) -> None: ...
    def addItem(self, type_: str, name: str, path: str) -> None: ...
    def delItem(self, type_: str, name: str) -> None: ...
    def clearItems(self, type_: str) -> None: ...
    def swapItems(self, type_: str, name1: str, name2: str) -> None: ...
    def collapseWindowsFromSystem(self) -> None: ...
    def collapseWindowsFromUser(self) -> None: ...
    def expandWindowsFromSystem(self) -> None: ...
    def collapseSettings(self) -> None: ...
    def expandSettings(self) -> None: ...
    def changeIdentify(self, type_1: str, type_2: str) -> None: ...
    def setAniSpeed(self, value: int) -> None: ...
    def setAlwaysOnEdge(self, state: bool) -> None: ...
    def setHasDraggingWidget(self, flag: bool) -> None: ...
    def setHasActivePopup(self, flag: bool) -> None: ...
    def setNTitleIconSize(self, titleIconSize: int) -> None: ...
    def setLock(self, flag: bool) -> None: ...
    def setPlacementSpinBoxBlockSig(self, flag: bool) -> None: ...
    def setPlacementSpinBoxValue(self, value: int) -> None: ...
    def setCollapseOnOpen(self, flag: bool) -> None: ...
    def setNAppIconSize(self, appIconSize: int) -> None: ...
    def setOpacity(self, arg_1: str, value: float) -> None: ...
    def setPlacement(self, placement: str | int) -> None: ...
    def setWindowsSize(self, arg_1: str, arg_2: int, value: int) -> None: ...
    def setWindowsTop(self, state: bool = None) -> None: ...
    def updateGeometriesState(self) -> None: ...
